// Cloudflare binding types, normally generated by `npm run cf:typegen`
// (wrangler types). Written by hand here because the sandboxed dev
// environment can't spawn the subprocess that step needs — regenerate with
// the real command once you're on a machine that can run it, to keep this
// in sync with wrangler.jsonc.
//
// These come in via `import type` rather than a triple-slash reference or
// tsconfig's `types` array on purpose: pulling in the whole
// @cloudflare/workers-types package globally redeclares Request/Response
// (Body.json() becomes `unknown` instead of `any`), which breaks every
// `NextRequest`/`NextResponse` call site across the app.
import type { D1Database, Fetcher } from "@cloudflare/workers-types";

export {};

declare global {
  interface CloudflareEnv {
    DB: D1Database;
    ASSETS: Fetcher;
    ADMIN_PASSWORD: string;
    SESSION_SECRET: string;
  }
}
